name: Development

on:
  push:
    branches: 
      - master
#     tags:
#       - "*"
  pull_request:
    branches:  
      - master 
  

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -o release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
        name: expense-artifact
        path: release/ # or path/to/artifact
  
  package:
    name: "Package and push"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: expense-artifact
      - name: Get the version
        id: get_version
        run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Buld and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./expense-artifact/Dockerfile
          repository: joydeep1985/expense
          #tags: ${{ steps.get_version.outputs.BRANCH  }}-${{ github.sha }}
          tags: latest
      
